version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    labels: [dependencies, automerge]
    open-pull-requests-limit: 5
    groups:
      actions:
        patterns: ["*"]
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
      day: monday
    labels: [dependencies, automerge]
    open-pull-requests-limit: 5
    groups:
      python:
        patterns: ["*"]
