[package]
version = "0.1.0"
authors =["Toolkit Agent <agent@example.com>"]
title = "RTX Remix Scatter Brush (UI)"
description = "Scatter Brush UI panel and hotkey integration for RTX Remix."
readme = "docs/README.md"
repository = "https://example.com/lightspeed.trex.tools.scatter_brush"
category = "internal"
keywords = ["remix", "scatter", "brush", "tools"]

[dependencies]
"omni.ui" = {}
"carb" = {}
"carb.settings" = {}
"omni.kit.hotkeys.core" = {}
"omni.flux.utils.common" = {}
"omni.flux.utils.widget" = {}
"lightspeed.trex.utils.widget" = {}
"lightspeed.trex.hotkeys" = {}
# Optional: leverage existing toolbar button if present
"lightspeed.trex.viewports.shared.widget" = {}

[[python.module]]
name = "lightspeed.trex.tools.scatter_brush"

[settings]
# Persisted defaults for scatter brush UI
exts."lightspeed.trex.tools.scatter_brush".enabled = false
exts."lightspeed.trex.tools.scatter_brush".asset_usd_path = ""
exts."lightspeed.trex.tools.scatter_brush".brush_radius = 0.25
exts."lightspeed.trex.tools.scatter_brush".spacing = 0.5
exts."lightspeed.trex.tools.scatter_brush".density = 8.0
exts."lightspeed.trex.tools.scatter_brush".random_scale_min = 0.9
exts."lightspeed.trex.tools.scatter_brush".random_scale_max = 1.1
exts."lightspeed.trex.tools.scatter_brush".random_yaw = true
exts."lightspeed.trex.tools.scatter_brush".align_to_normals = true
exts."lightspeed.trex.tools.scatter_brush".max_surface_angle_deg = 45.0
exts."lightspeed.trex.tools.scatter_brush".seed = 1337
exts."lightspeed.trex.tools.scatter_brush".erase_mode = false
exts."lightspeed.trex.tools.scatter_brush".category = ""
# Optional index path for pre-ingested prototypes
exts."lightspeed.trex.tools.scatter_brush".prototypes_index = ""