[package]
version = "0.1.0"
authors =["Toolkit Agent <agent@example.com>"]
title = "RTX Remix Scatter Brush (UI)"
description = "Scatter Brush UI panel and hotkey integration for RTX Remix."
readme = "docs/README.md"
repository = "https://example.com/lightspeed.trex.tools.scatter_brush"
category = "internal"
keywords = ["remix", "scatter", "brush", "tools"]

[dependencies]
"omni.ui" = {}
"omni.kit.hotkeys.core" = {}
"omni.flux.utils.common" = {}
"omni.flux.utils.widget" = {}
"lightspeed.trex.utils.widget" = {}
"lightspeed.trex.hotkeys" = {}
# Optional: leverage existing toolbar button if present
"lightspeed.trex.viewports.shared.widget" = {}

[[python.module]]
name = "lightspeed.trex.tools.scatter_brush"

[settings]
# Persisted defaults for scatter brush UI
[settings.exts."lightspeed.trex.tools.scatter_brush"]
enabled = false
asset_usd_path = ""
brush_radius = 0.25
spacing = 0.5
density = 8.0
random_scale_min = 0.9
random_scale_max = 1.1
random_yaw = true
align_to_normals = true
max_surface_angle_deg = 45.0
seed = 1337
erase_mode = false
category = ""
# Optional index path for pre-ingested prototypes
prototypes_index = ""
