name: Auto Triage

on:
  workflow_call:
    inputs:
      artifacts_path:
        description: 'Path to artifacts folder with test results'
        required: true
        type: string

permissions:
  contents: read
  issues: write

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts (skipped - expects local path)
        run: echo "Using artifacts at ${{ inputs.artifacts_path }}"
      - name: Check for failures and open issue
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = require('path');
            const artifactsPath = `${{ inputs.artifacts_path }}`;
            const junit = path.join(artifactsPath, 'test-results.xml');
            if (!fs.existsSync(junit)) {
              core.info('No JUnit results found. Skipping.');
              return;
            }
            const content = fs.readFileSync(junit, 'utf8');
            const hasFailures = /failures=\"([1-9][0-9]*)\"/.test(content) || /errors=\"([1-9][0-9]*)\"/.test(content);
            if (!hasFailures) {
              core.info('No failures detected.');
              return;
            }
            const title = `Test failures detected in ${context.workflow} run ${context.runId}`;
            const body = `Automated triage detected test failures.\n\nRun: https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`;
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title,
              body
            });